### PR TITLE
Add s3 bucket metric

### PR DESCRIPTION
**Pull request by duncan9562**

### CODE REVIEW

**Comment by ianrelf** [comment]
Any reason for using a dash rather than an underscore?
"haprox_config_bucket-logging"

**Comment by ianrelf** [comment]
Is it correct to use:
`
bucket = "${var.s3_bucket_name}"
`

When that variable appears to be blank:
`
variable "s3_bucket_name" {}
`
(from: dq-tf-peering-haproxy/variable.tf)

**Comment by duncan9562** [comment]
`bucket = "${var.s3_bucket_name}"` is correct. Due to the structure the modules in Terraform, this variable is actually defined in `dq-tf-infra/peering.tf', where `dq-tf-peering-haproxy`is a sub module.

**Comment by ianrelf** [comment]
LGTM

**Pull request merged**
